### ISSUE TITLE
java.lang.ClassNotFoundException: org.ontoware.rdf2go.impl.StaticBinding

### ISSUE THREAD

**Issue by luispcosta** [jsonld-java/jsonld-java-rdf2go#2]
Hello.

I'm trying to use your API to convert a json-ld file to rdf/xml syntax.

This is what I've done so far:

In my `pom.xml`:

``` xml
<dependency>
    <groupId>com.github.jsonld-java</groupId>
    <artifactId>jsonld-java-rdf2go</artifactId>
    <version>0.7.0</version>
</dependency>
```

I had to remove the `-SNAPSHOT` from the version otherwise eclipse reports me the following error:

`Missing artifact com.github.jsonld-java:jsonld-java-rdf2go:jar:0.7.0-SNAPSHOT`

I have a json-ld file called `my.json` file:

``` json
{
  "@context": {
    "dc": "http://purl.org/dc/elements/1.1/",
    "owl": "http://www.w3.org/2002/07/owl#",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "@graph": [
    {
      "@id": "http://www.semanticweb.org/lpec/ontologies/2015/9/testing#Class_H",
      "@type": "owl:Class",
      "rdfs:subClassOf": {
        "@id": "http://www.semanticweb.org/lpec/ontologies/2015/9/testing#Class_E"
      }
    },
    {
      "@id": "http://www.semanticweb.org/lpec/ontologies/2015/9/testing#Class_I",
      "@type": "owl:Class",
      "rdfs:subClassOf": {
        "@id": "http://www.semanticweb.org/lpec/ontologies/2015/9/testing#Class_G"
      }
    },
    {
      "@id": "http://www.eswc2006.org/technologies/ontology#",
      "@type": [
        "owl:NamedIndividual",
        "owl:Thing"
      ]
    },
    {
      "@id": "http://www.semanticweb.org/lpec/ontologies/2015/9/testing#Class_G",
      "@type": "owl:Class",
      "rdfs:subClassOf": {
        "@id": "http://www.semanticweb.org/lpec/ontologies/2015/9/testing#Class_E"
      }
    },
    {
      "@id": "http://www.semanticweb.org/lpec/ontologies/2015/9/testing#Class_D",
      "@type": "owl:Class",
      "rdfs:subClassOf": {
        "@id": "http://www.semanticweb.org/lpec/ontologies/2015/9/testing#ClassC"
      }
    },
    {
      "@id": "http://www.semanticweb.org/lpec/ontologies/2015/9/testing#Class_E",
      "@type": "owl:Class",
      "rdfs:subClassOf": {
        "@id": "http://www.semanticweb.org/lpec/ontologies/2015/9/testing#Class_D"
      }
    },
    {
      "@id": "http://www.semanticweb.org/lpec/ontologies/2015/9/testing#Class_F",
      "@type": "owl:Class",
      "rdfs:subClassOf": {
        "@id": "http://www.semanticweb.org/lpec/ontologies/2015/9/testing#Class_E"
      }
    },
    {
      "@id": "http://www.semanticweb.org/lpec/ontologies/2015/9/testing#ClassA",
      "@type": "owl:Class"
    },
    {
      "@id": "http://www.semanticweb.org/lpec/ontologies/2015/9/testing#ClassB",
      "@type": "owl:Class"
    },
    {
      "@id": "http://www.semanticweb.org/lpec/ontologies/2015/9/testing#ClassC",
      "@type": "owl:Class",
      "rdfs:subClassOf": {
        "@id": "http://www.semanticweb.org/lpec/ontologies/2015/9/testing#ClassA"
      }
    },
    {
      "@id": "http://www.semanticweb.org/lpec/ontologies/2015/9/testing",
      "@type": "owl:Ontology",
      "dc:contributor": "ESWC2006 Organising Committee",
      "dc:creator": "Tom Heath",
      "dc:date": "$Date: 2007-12-14 19:22:50 $",
      "dc:description": "An ontology for describing academic conferences, designed to support the 3rd European Semantic Web Conference (ESWC2006)\"",
      "dc:title": "The ESWC2006 Conference Ontology"
    }
  ]
}
```

Then I tried to follow your code from [this test](https://github.com/jsonld-java/jsonld-java-rdf2go/blob/master/src/test/java/com/github/jsonldjava/rdf2go/RDF2GoTripleCallbackTest.java) and I wrote the following code:

``` java
    // Yes the path is correct
    InputStream is = new FileInputStream("path/to/my.json");
    Object jsonObj = JsonUtils.fromInputStream(is);
    final RDF2GoTripleCallback cb = new RDF2GoTripleCallback();
    final ModelSet model = (ModelSet) JsonLdProcessor.toRDF(jsonObj, cb);
    model.dump();
```

There are my imports:

``` java
import org.ontoware.rdf2go.RDF2Go;
import org.ontoware.rdf2go.model.Model;
import org.ontoware.rdf2go.model.ModelSet;

import com.github.jsonldjava.core.JsonLdError;
import com.github.jsonldjava.core.JsonLdOptions;
import com.github.jsonldjava.core.JsonLdProcessor;
import com.github.jsonldjava.rdf2go.RDF2GoRDFParser;
import com.github.jsonldjava.rdf2go.RDF2GoTripleCallback;
import com.github.jsonldjava.utils.JsonUtils;
```

However when I try to run that code I get the error:

``` java
Exception in thread "main" org.ontoware.rdf2go.exception.ModelRuntimeException: java.lang.ClassNotFoundException: org.ontoware.rdf2go.impl.StaticBinding
    at org.ontoware.rdf2go.RDF2Go.checkModelFactory(RDF2Go.java:171)
    at org.ontoware.rdf2go.RDF2Go.getModelFactory(RDF2Go.java:93)
    at com.github.jsonldjava.rdf2go.RDF2GoTripleCallback.<init>(RDF2GoTripleCallback.java:25)
    at luispcosta.util.MongoTest.main(MongoTest.java:49)
Caused by: java.lang.ClassNotFoundException: org.ontoware.rdf2go.impl.StaticBinding
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at org.ontoware.rdf2go.RDF2Go.checkModelFactory(RDF2Go.java:161)
    ... 3 more
```

What can I do about this?

**Comment by ansell** [comment]
I am not overly familiar with the RDF2GO model, but I think you may need to select an implementation to use. Ie, do you want to use Jena or Sesame? Then also import the relevant module as well:

```
<dependency>
    <groupId>org.semweb4j</groupId>
    <artifactId>rdf2go.impl.sesame</artifactId>
    <version>5.0.1</version>
</dependency>
```

I will also fix the issue with the -SNAPSHOT and make it 0.7.0.

**Comment by luispcosta** [comment]
Hello. Thank you for your reply.

I included that dependency in my project, however, I'm still not able to execute the code listed. Do I need both dependencies? i.e, do I need

``` xml
<dependency>
    <groupId>com.github.jsonld-java</groupId>
    <artifactId>jsonld-java-rdf2go</artifactId>
    <version>0.7.0</version>
</dependency>
```

and 

``` xml
<dependency>
    <groupId>org.semweb4j</groupId>
    <artifactId>rdf2go.impl.sesame</artifactId>
    <version>5.0.1</version>
</dependency>
```

Or only the latter one? By using only the latter one, I can't import the classes into the project:

``` java
import com.github.jsonldjava.rdf2go.RDF2GoRDFParser;
import com.github.jsonldjava.rdf2go.RDF2GoTripleCallback;
```

**Comment by luispcosta** [comment]
Nevermind, I included both dependencies and it's working!

Thank you for the help, you can close the issue

**Comment by ansell** [comment]
No problems
